name: Build Client

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            goos: linux
            goarch: amd64
            binary_ext: ""
          - os: windows-latest
            platform: windows
            goos: windows
            goarch: amd64
            binary_ext: ".exe"
          - os: macos-latest
            platform: darwin
            goos: darwin
            goarch: amd64
            binary_ext: ""
    steps:
      - uses: actions/checkout@v4
      - name: 安装GO
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.12.0"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: 安装 Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: 安装前端 dependencies 依赖
        working-directory: ./frontend
        run: npm ci

      - name: Get Go dependencies
        run: go mod download

      - name: Configure Go environment
        run: |
          echo "GOOS=${{ matrix.goos }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.goarch }}" >> $GITHUB_ENV

      - name: Build for ${{ matrix.platform }}
        run: wails build -clean -platform ${{ matrix.platform }}/amd64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: go-git-client-${{ matrix.platform }}
          path: build/bin/
          retention-days: 30

